hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 37003

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/uaa/users/current

name: config-server
